In [ ]:
# Q1: Create a DataFrame with the following e-commerce sales data: 
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review 
# Create at least 50 sample records with realistic data including dates from 2023-2024 
# Display the first 10 and last 5 records using head() and tail() 

# Q2: Use info() and describe() to get a comprehensive overview of the dataset 
# Identify data types, missing values, and statistical summary 
# Print the column names using columns attribute and shape of the dataset 

# Q3: Introduce 10% missing values randomly in Rating and Review columns 
# Detect missing values and display the count of missing values per column 
# Fill missing ratings with the median rating and missing reviews with "No review provided" 

# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price 
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $100 
# Use conditional selection to filter orders where TotalAmount > $150 

# Q5: Select only the columns: Product, Category, TotalAmount, and Rating 
# Filter and display all orders from the 'Electronics' category with Rating >= 4 

# Q6: Use boolean indexing to find all orders where: 
# - Quantity > 2 AND Price < 50 OR Rating == 5 
# Display the count of such orders 

# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending) 
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order 

# Q8: Find the top 5 best-selling products based on total quantity sold 
# Display the product name and total quantity in descending order 


# PART 5: GROUPING & AGGREGATION (Statistical Analysis) 
# Q9: Group the data by 'Category' and calculate: 
# - Total sales (sum of TotalAmount) 
# - Average rating 
# - Number of orders 
# Display the results sorted by total sales 

# Q10: Create a pivot table showing average Price for each Category and Rating combination 
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions 

# Q11: Convert the Quantity and Price columns to NumPy arrays 
# Create a 2D array combining these two columns 
# Display array properties: shape, dtype, ndim, size 

# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500 
# Calculate mean, median, standard deviation, min, and max using NumPy functions 
# Reshape this array into a 10x10 matrix 

# Q13: Create two 3D NumPy arrays (3x3x3) with random integers 
# Perform element-wise addition, multiplication, and matrix multiplication 
# Use boolean indexing to filter values greater than 50 

# Q14: Create NumPy arrays using special values: 
# - Array of zeros (5x5) 
# - Array of ones (3x4) 
# - Identity matrix (4x4) 
# - Array with values from 0 to 50 with step of 5 using arange 
# Concatenate and stack these arrays 

# Q15: Use array slicing to extract: 
# - First 3 rows from the Quantity-Price 2D array 
# - Every alternate element from the Price array 
# - Diagonal elements from a 5x5 matrix of TotalAmount values 

# Q16: Create a correlation matrix between Quantity, Price, Rating, and TotalAmount using NumPy 
# Calculate the covariance matrix 
# Perform linear algebra operations: determinant and inverse of correlation matrix 

# Q17: Generate 1000 random samples from a normal distribution (mean=100, std=15) 
# Calculate percentiles: 25th, 50th, 75th, 90th, 95th 
# Demonstrate the difference between copy and view using these arrays 

# Q18: Create a random array of 1000 sales values 
# Use NumPy to flatten, reshape into (100, 10), and then transpose 
# Compare memory usage between original, copy, and view 

# Q19: Create a line plot showing total sales trend over months 
# Customize with: title, xlabel, ylabel, grid, legend 
# Use different line styles, colors, and markers 

# Q20: Create a bar chart comparing total sales across different categories 
# Customize colors for each bar and add value labels on top of bars 
# Create a horizontal bar chart as well 

# Q21: Create a scatter plot showing relationship between Price and Rating 
# Color points by Category and vary point size by Quantity 
# Add a trend line and customize markers 

# Q22: Create a histogram showing the distribution of TotalAmount 
# Use 20 bins and customize colors and transparency 
# Add a vertical line showing the mean value 

# Q23: Create a pie chart showing percentage distribution of sales by Category 
# Explode the largest segment and display percentages 
# Customize colors and add a legend 

# Q24: Create a 2x2 subplot figure containing: 
# - Top-left: Sales trend line plot 
# - Top-right: Category-wise bar chart 
# - Bottom-left: Rating distribution histogram 
# - Bottom-right: Sales by category pie chart 
# Save this dashboard as 'sales_dashboard.png' with 300 dpi 

# Q25: Create a comprehensive mini-dashboard (3x2 subplots) that includes: 
# - Sales over time, Category comparison, Price vs Rating scatter
# - Quantity distribution, Top 5 products bar chart, Monthly growth line 
# Customize each subplot with titles, labels, and legends 

# Q26: Create a second DataFrame with customer information: 
# Columns: CustomerID, CustomerName, City, SignupDate 
# Merge this with the sales DataFrame using CustomerID (inner, left, right, outer joins) 
# Demonstrate the difference between merge and join operations 
# Q27: Create three separate DataFrames for three different months of sales data 
# Concatenate them vertically (along rows) and horizontally (along columns)
# Remove duplicate records if any and reset the index 

# Q28: Convert OrderDate column to datetime format 
# Extract: Year, Month, Day, DayOfWeek, Quarter from OrderDate 
# Create a time series analysis showing sales trends by month and quarter 
# Calculate rolling 7-day average of sales 

# Q29: Using the Review column, perform comprehensive text analysis: 
# - Tokenize all reviews into words 
# - Remove stopwords from reviews 
# - Apply stemming and lemmatization 
# - Perform POS tagging on sample reviews 
# - Create frequency distribution of top 20 most common words 
# - Visualize word frequency using a bar chart 

# Q30: Convert Quantity, Price, and Rating columns to TensorFlow tensors 
# Create TensorFlow variables for Price and update them with 15% price increase 
# Perform tensor operations: 
# - Calculate predicted revenue using matrix multiplication 
# - Apply mathematical functions (square, sqrt, exponential) on tensors 
# - Demonstrate in-place operations and variable updates 
# Display tensor properties: shape, dtype, rank 

# After completing all analysis, export the final cleaned and processed DataFrame to: 
# - CSV file: 'final_sales_analysis.csv' 
# Include only relevant columns and exclude any temporary columns created during analysis 

In [1]:
import pandas as pd

In [18]:
# Q1: Create a DataFrame with the following e-commerce sales data: 
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review 
# Create at least 50 sample records with realistic data including dates from 2023-2024 
# Display the first 10 and last 5 records using head() and tail() 
df = pd.read_csv('mahalaxmi_foods.csv')
print(f"first ten records: \n{df.head(10)}")
print(f"last five records: \n{df.tail(5)}")


first ten records: 
  OrderID CustomerID              Product Category  Quantity  Price  \
0   D-001   CUST-001  Bhajake Pohe Chiwda   Chiwda    1000.0  600.0   
1   D-002   CUST-002     Chakali(Bhajani)  Chakali    1500.0  600.0   
2   D-003   CUST-003     Chakali(Bhajani)  Chakali    1000.0  600.0   
3   D-004   CUST-004           Rava Ladoo    Ladoo     500.0  650.0   
4   D-005   CUST-005    Patal Pohe Chiwda   Chiwda     125.0  600.0   
5   D-006   CUST-006     Chakali(Bhajani)  Chakali     500.0  600.0   
6   D-007   CUST-007  Bhajake Pohe Chiwda   Chiwda    1000.0  600.0   
7   D-008   CUST-008     Chakali(Bhajani)  Chakali     500.0  600.0   
8   D-009   CUST-009     Chakali(Bhajani)  Chakali    1000.0  600.0   
9   D-010   CUST-010     Chakali(Bhajani)  Chakali     500.0  600.0   

    OrderDate  Rating              Review  
0  2025-10-14     3.0   Loved the texture  
1  2025-10-19     5.0                 NaN  
2  2025-10-19     4.0  Packaging was good  
3  2025-10-17     3.0 

In [15]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset 
# Identify data types, missing values, and statistical summary 
# Print the column names using columns attribute and shape of the dataset 
print(df.info())
print(df.describe())
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   OrderID     150 non-null    object 
 1   CustomerID  150 non-null    object 
 2   Product     150 non-null    object 
 3   Category    150 non-null    object 
 4   Quantity    150 non-null    float64
 5   Price       150 non-null    float64
 6   OrderDate   150 non-null    object 
 7   Rating      122 non-null    float64
 8   Review      63 non-null     object 
dtypes: float64(3), object(6)
memory usage: 10.7+ KB
None
           Quantity       Price      Rating
count    150.000000  150.000000  122.000000
mean    1119.500000  611.333333    3.975410
std     2578.451733   74.892914    0.827853
min      125.000000  300.000000    3.000000
25%      500.000000  600.000000    3.000000
50%      500.000000  600.000000    4.000000
75%     1000.000000  650.000000    5.000000
max    30000.000000  800.000000    

In [21]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns 
# Detect missing values and display the count of missing values per column 
# Fill missing ratings with the median rating and missing reviews with "No review provided" 

df['Rating'] = df['Rating'].fillna(df['Rating'].median())
df['Review'] = df['Review'].fillna("No review provided")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   OrderID          150 non-null    object 
 1   CustomerID       150 non-null    object 
 2   Product          150 non-null    object 
 3   Category         150 non-null    object 
 4   Quantity         150 non-null    float64
 5   Price            150 non-null    float64
 6   OrderDate        150 non-null    object 
 7   Rating           150 non-null    float64
 8   Review           150 non-null    object 
 9   TotalAmount      150 non-null    float64
 10  DiscountedPrice  150 non-null    float64
dtypes: float64(5), object(6)
memory usage: 13.0+ KB
None


In [23]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price 
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $100 
# Use conditional selection to filter orders where TotalAmount > $150 
df['TotalAmount'] = (df['Quantity'] * df['Price']) / 1000
df['DiscountedPrice'] = df['TotalAmount'].apply(lambda x: x * 0.9 if x > 1000 else x)
print(df)
filtered_orders = df[df['TotalAmount'] > 1500]
print("Orders Above 1500rs")
print(filtered_orders)

    OrderID CustomerID              Product     Category  Quantity  Price  \
0     D-001   CUST-001  Bhajake Pohe Chiwda       Chiwda    1000.0  600.0   
1     D-002   CUST-002     Chakali(Bhajani)      Chakali    1500.0  600.0   
2     D-003   CUST-003     Chakali(Bhajani)      Chakali    1000.0  600.0   
3     D-004   CUST-004           Rava Ladoo        Ladoo     500.0  650.0   
4     D-005   CUST-005    Patal Pohe Chiwda       Chiwda     125.0  600.0   
..      ...        ...                  ...          ...       ...    ...   
145   D-080   CUST-025     Chakali(Bhajani)      Chakali     500.0  600.0   
146   D-080   CUST-025   Shankarpali(Sweet)  Shankarpali     500.0  600.0   
147   D-081   CUST-073     Chakali(Bhajani)      Chakali     500.0  600.0   
148   D-081   CUST-073          Besan Ladoo        Ladoo     500.0  750.0   
149   D-082   CUST-074     Chakali(Bhajani)      Chakali     500.0  600.0   

      OrderDate  Rating              Review  TotalAmount  DiscountedPrice  

In [27]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating 
# Filter and display all orders from the 'Electronics' category with Rating >= 4 
selected_df = df[['Product', 'Category', 'TotalAmount','Rating' ]]
print(selected_df)
filtered_ladoo = selected_df[(selected_df['Category'] == 'Ladoo') & (selected_df['Rating'] >=4.0)]
print(filtered_ladoo)

                 Product     Category  TotalAmount  Rating
0    Bhajake Pohe Chiwda       Chiwda        600.0     3.0
1       Chakali(Bhajani)      Chakali        900.0     5.0
2       Chakali(Bhajani)      Chakali        600.0     4.0
3             Rava Ladoo        Ladoo        325.0     3.0
4      Patal Pohe Chiwda       Chiwda         75.0     4.0
..                   ...          ...          ...     ...
145     Chakali(Bhajani)      Chakali        300.0     4.0
146   Shankarpali(Sweet)  Shankarpali        300.0     3.0
147     Chakali(Bhajani)      Chakali        300.0     4.0
148          Besan Ladoo        Ladoo        375.0     5.0
149     Chakali(Bhajani)      Chakali        300.0     4.0

[150 rows x 4 columns]
          Product Category  TotalAmount  Rating
41    Besan Ladoo    Ladoo        750.0     5.0
53     Oats Ladoo    Ladoo        400.0     5.0
73     Rava Ladoo    Ladoo        650.0     5.0
74    Besan Ladoo    Ladoo        750.0     4.0
80     Rava Ladoo    Ladoo  

In [29]:
# Q6: Use boolean indexing to find all orders where: 
# - Quantity > 2 AND Price < 50 OR Rating == 5 
# Display the count of such orders 
filtered_1 = df[(df['Quantity'] > 2000) & (df['Price'] > 500) | (df['Rating'] == 5.0)]
print(f"No of orders according to filter: {len(filtered_1)}")
print(filtered_1)

No of orders according to filter: 44
    OrderID CustomerID               Product     Category  Quantity  Price  \
1     D-002   CUST-002      Chakali(Bhajani)      Chakali    1500.0  600.0   
11    D-012   CUST-012      Chakali(Bhajani)      Chakali   30000.0  600.0   
12    D-013   CUST-013      Chakali(Bhajani)      Chakali    4000.0  600.0   
14    D-015   CUST-015      Chakali(Bhajani)      Chakali   10000.0  600.0   
15    D-016   CUST-016      Chakali(Bhajani)      Chakali    1000.0  600.0   
16    D-017   CUST-017      Chakali(Bhajani)      Chakali     750.0  600.0   
17    D-018   CUST-018    Shankarpali(Sweet)  Shankarpali    1500.0  600.0   
20    D-021   CUST-021               Karanji      Karanji    3000.0  700.0   
23    D-024   CUST-030   Bhajake Pohe Chiwda       Chiwda     500.0  600.0   
24    D-025   CUST-024      Chakali(Bhajani)      Chakali    2000.0  600.0   
26    D-027   CUST-026               Karanji      Karanji    1000.0  700.0   
27    D-028   CUST-027     

In [30]:
# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending) 
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order 
df_sorted = df.sort_values(by=['OrderDate', 'TotalAmount'], ascending=False)
df_sorted['SalesRank'] = df_sorted['TotalAmount'].rank(ascending=False, method='min')
print(df_sorted)

   OrderID CustomerID              Product Category  Quantity  Price  \
54   D-055   CUST-050  Bhajake Pohe Chiwda   Chiwda    1250.0  600.0   
55   D-055   CUST-050         Boondi Ladoo    Ladoo    1250.0  550.0   
4    D-005   CUST-005    Patal Pohe Chiwda   Chiwda     125.0  600.0   
7    D-008   CUST-008     Chakali(Bhajani)  Chakali     500.0  600.0   
36   D-040   CUST-037     Chakali(Bhajani)  Chakali    2000.0  600.0   
..     ...        ...                  ...      ...       ...    ...   
18   D-019   CUST-019     Chakali(Bhajani)  Chakali    1000.0  600.0   
19   D-020   CUST-020             A1 ladoo    Ladoo     300.0  800.0   
11   D-012   CUST-012     Chakali(Bhajani)  Chakali   30000.0  600.0   
10   D-011   CUST-011     Chakali(Bhajani)  Chakali    1000.0  600.0   
6    D-007   CUST-007  Bhajake Pohe Chiwda   Chiwda    1000.0  600.0   

     OrderDate  Rating              Review  TotalAmount  DiscountedPrice  \
54  2025-10-23     4.0  No review provided        750.0    

In [33]:
# Q8: Find the top 5 best-selling products based on total quantity sold 
# Display the product name and total quantity in descending order 

product_sales = df.groupby('Product')['Quantity'].sum().reset_index()

top_5_products = product_sales.sort_values(by='Quantity', ascending=False).head(5)

print(top_5_products)

                Product  Quantity
5      Chakali(Bhajani)   90750.0
7               Karanji   14500.0
4          Boondi Ladoo    9250.0
3   Bhajake Pohe Chiwda    7250.0
14   Shankarpali(Sweet)    7250.0


In [34]:
# Q9: Group the data by 'Category' and calculate: 
# - Total sales (sum of TotalAmount) 
# - Average rating 
# - Number of orders 
# Display the results sorted by total sales 

category_summary = df.groupby('Category').agg(
    Total_Sales=('TotalAmount', 'sum'),
    Average_Rating=('Rating', 'mean'),
    Order_Count=('OrderID', 'count')
)
category_summary = category_summary.sort_index().sort_values(by='Total_Sales', ascending=False)

print(category_summary)

             Total_Sales  Average_Rating  Order_Count
Category                                             
Chakali          54450.0        3.923077           52
Ladoo            13665.0        4.083333           24
Karanji          10150.0        3.875000           16
Chiwda            7975.0        4.200000           20
Shankarpali       6225.0        4.176471           17
Shev              3875.0        3.727273           11
Anarase           2800.0        3.777778            9
Other             1500.0        3.000000            1


In [36]:
# Q10: Create a pivot table showing average Price for each Category and Rating combination 
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions 

pivot_price = df.pivot_table(
    values='Price', 
    index='Category', 
    columns='Rating', 
    aggfunc='mean'
)

multi_group = df.groupby(['Category', 'Product']).agg({
    'TotalAmount': ['sum', 'mean'],
    'Quantity': 'sum',
    'Rating': 'mean'
})

print("Pivot Table: Avg Price by Category & Rating")
print(pivot_price)
print("Multi-Column Groupby Aggregation")
print(multi_group)

Pivot Table: Avg Price by Category & Rating
Rating              3.0         4.0         5.0
Category                                       
Anarase      700.000000  700.000000  700.000000
Chakali      600.000000  600.000000  600.000000
Chiwda       550.000000  583.333333  583.333333
Karanji      700.000000  700.000000  700.000000
Ladoo        671.428571  637.500000  700.000000
Other        300.000000         NaN         NaN
Shankarpali  550.000000  550.000000  571.428571
Shev         500.000000  500.000000  500.000000
Multi-Column Groupby Aggregation
                                 TotalAmount              Quantity    Rating
                                         sum         mean      sum      mean
Category    Product                                                         
Anarase     Anarase                   2800.0   311.111111   4000.0  3.777778
Chakali     Chakali(Bhajani)         54450.0  1047.115385  90750.0  3.923077
Chiwda      Bhajake Pohe Chiwda       4350.0   483.333333 

In [37]:
# Q11: Convert the Quantity and Price columns to NumPy arrays 
# Create a 2D array combining these two columns 
# Display array properties: shape, dtype, ndim, size
import numpy as np
quantity_arr = np.array(df['Quantity'])
price_arr = np.array(df['Price'])
combined_arr = np.column_stack((quantity_arr, price_arr))
print("Array: \n", combined_arr)
print(f"Shape: {combined_arr.shape}")
print(f"dtype: {combined_arr.dtype}")
print(f"ndim: {combined_arr.ndim}")
print(f"size: {combined_arr.size}")



Array: 
 [[ 1000.   600.]
 [ 1500.   600.]
 [ 1000.   600.]
 [  500.   650.]
 [  125.   600.]
 [  500.   600.]
 [ 1000.   600.]
 [  500.   600.]
 [ 1000.   600.]
 [  500.   600.]
 [ 1000.   600.]
 [30000.   600.]
 [ 4000.   600.]
 [ 1000.   600.]
 [10000.   600.]
 [ 1000.   600.]
 [  750.   600.]
 [ 1500.   600.]
 [ 1000.   600.]
 [  300.   800.]
 [ 3000.   700.]
 [ 1000.   600.]
 [ 2000.   600.]
 [  500.   600.]
 [ 2000.   600.]
 [ 2000.   600.]
 [ 1000.   700.]
 [  500.   600.]
 [ 1000.   600.]
 [  500.   600.]
 [  500.   600.]
 [ 1500.   600.]
 [ 1000.   600.]
 [  500.   500.]
 [ 1000.   600.]
 [ 1500.   550.]
 [ 2000.   600.]
 [  250.   700.]
 [ 3000.   600.]
 [  500.   600.]
 [ 2500.   700.]
 [ 1000.   750.]
 [  500.   700.]
 [  500.   700.]
 [  500.   600.]
 [  500.   600.]
 [ 1000.   600.]
 [  500.   600.]
 [ 1000.   600.]
 [  250.   500.]
 [  500.   600.]
 [  500.   700.]
 [  500.   700.]
 [  500.   800.]
 [ 1250.   600.]
 [ 1250.   550.]
 [ 1000.   600.]
 [  500.   700.]
 [  7

In [38]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500 
# Calculate mean, median, standard deviation, min, and max using NumPy functions 
# Reshape this array into a 10x10 matrix 
rand_prices = np.random.uniform(10,500,100)
print(f"Mean: {np.mean(rand_prices)}")
print(f"median: {np.median(rand_prices)}")
print(f"standard deviation: {np.std(rand_prices)}")
print(f"min: {np.min(rand_prices)}")
print(f"max: {np.max(rand_prices)}")
rand_prices_matrix = rand_prices.reshape(10,10)
print(rand_prices_matrix)

Mean: 272.6746543704302
median: 280.32244184797605
standard deviation: 147.45075326974782
min: 16.329729011603813
max: 498.38795269476293
[[251.40537334 451.18908968 213.36058748 433.59831378 331.64193207
  252.09137162  42.11386719 344.88738271 438.93267964 283.39296612]
 [315.83510989  46.98084091 256.66800057 334.9945355  271.57959724
  154.65705301  82.20068219  17.41929718  64.57832537 115.57691841]
 [417.57148758 254.52291505 298.37196476 204.32798821 220.25201869
  219.77898794 430.25610736 357.13589756 180.28317983 216.41777195]
 [ 61.23412498 221.60101784  52.36584411  89.53845882 312.39329685
  436.4783298  425.29578223 103.85771159 461.23396296 102.82266694]
 [457.25585169 279.14374054 181.83879396 427.06281774  89.19544423
  361.75485531 378.58787065 498.20244723  93.4516195  498.38795269]
 [468.83384389  16.32972901 458.44247294 241.78129889 347.31965862
  401.87454388 251.57995675 491.25393165 281.50114316 490.35896114]
 [ 92.30507543 197.59691711 305.74579855 395.5185717

In [39]:
# Q13: Create two 3D NumPy arrays (3x3x3) with random integers 
# Perform element-wise addition, multiplication, and matrix multiplication 
# Use boolean indexing to filter values greater than 50 
import numpy as np

array1 = np.random.randint(1, 101, size=(3, 3, 3))
array2 = np.random.randint(1, 101, size=(3, 3, 3))

addition_result = np.add(array1, array2)

elementwise_mult_result = np.multiply(array1, array2)

matrix_mult_result = np.matmul(array1, array2)

filtered_values = array1[array1 > 50]

print("--- Array 1 ---")
print(array1)
print("\n--- Matrix Multiplication Result ---")
print(matrix_mult_result)
print("\n--- Values > 50 in Array 1 ---")
print(filtered_values)

--- Array 1 ---
[[[82 55 99]
  [20 97 42]
  [73 54 14]]

 [[60 47 18]
  [95 22 48]
  [55 46 83]]

 [[52 21 99]
  [23 66 67]
  [20 27 61]]]

--- Matrix Multiplication Result ---
[[[16401  7688 13973]
  [ 8677  4248 13147]
  [ 9618  2625  6859]]

 [[ 8551  4127  9321]
  [12031  7057 12236]
  [11234 10107 11388]]

 [[ 8032  5181  7100]
  [ 8415  7628  5149]
  [ 5592  4259  4084]]]

--- Values > 50 in Array 1 ---
[82 55 99 97 73 54 60 95 55 83 52 99 66 67 61]


In [40]:
# Q14: Create NumPy arrays using special values: 
# - Array of zeros (5x5) 
# - Array of ones (3x4) 
# - Identity matrix (4x4) 
# - Array with values from 0 to 50 with step of 5 using arange 
# Concatenate and stack these arrays 

zeros_5x5 = np.zeros((5, 5))
ones_3x4 = np.ones((3, 4))
identity_4x4 = np.eye(4)  # np.eye creates the Identity Matrix
range_array = np.arange(0, 51, 5) # [0, 5, 10 ... 50]

arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])

concat_v = np.concatenate((arr_a, arr_b), axis=0) # Vertical join
concat_h = np.concatenate((arr_a, arr_b), axis=1) # Horizontal join

stacked = np.stack((arr_a, arr_b))
print("Array of zeros (5x5): \n ", zeros_5x5)
print("Array of ones (3x4) :\n", ones_3x4)
print("Identity matrix (4x4) :\n", identity_4x4)
print("Array with values from 0 to 50 with step of 5 using arange :\n", range_array)
print("Vertical Concatenation :\n", concat_v)
print("Horizontal Concatenation :\n", concat_h)
print("Stacked :\n", stacked)


Array of zeros (5x5): 
  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array of ones (3x4) :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix (4x4) :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array with values from 0 to 50 with step of 5 using arange :
 [ 0  5 10 15 20 25 30 35 40 45 50]
Vertical Concatenation :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation :
 [[1 2 5 6]
 [3 4 7 8]]
Stacked :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Q15: Use array slicing to extract: 
# - First 3 rows from the Quantity-Price 2D array 
# - Every alternate element from the Price array 
# - Diagonal elements from a 5x5 matrix of TotalAmount values 
total_amount_arr = np.array(df['TotalAmount'].head(25))
total_amount_arr_5x5 = total_amount_arr.reshape(5,5)



first_three_rows = combined_arr[:3, :]
print("First 3 rows from the Quantity-Price 2D array :",first_three_rows)

alternate_prices = price_arr[::2]
print("Every alternate element from the Price array  :",alternate_prices)

diagonal_elements = np.diag(total_amount_arr_5x5)
print("Diagonal elements from a 5x5 matrix of TotalAmount values   :",diagonal_elements)

First 3 rows from the Quantity-Price 2D array : [[1000.  600.]
 [1500.  600.]
 [1000.  600.]]
Every alternate element from the Price array  : [600. 600. 600. 600. 600. 600. 600. 600. 600. 600. 700. 600. 600. 700.
 600. 600. 600. 600. 600. 600. 700. 700. 600. 600. 600. 600. 700. 600.
 600. 600. 500. 600. 600. 600. 500. 700. 600. 750. 700. 600. 650. 600.
 500. 650. 600. 500. 500. 600. 500. 600. 550. 750. 600. 700. 600. 500.
 750. 700. 300. 550. 700. 600. 600. 650. 700. 700. 500. 600. 750. 600.
 750. 550. 650. 600. 750.]
Diagonal elements from a 5x5 matrix of TotalAmount values   : [ 600.  600. 2400.  600. 1200.]
